version: '3.8'

services:
  php:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    stdin_open: true # docker run -i
    tty: true        # docker run -t
